### ISSUE TITLE
js7 agent windows 2.7.0 keepass support is broken

### ISSUE THREAD

**Issue by kregory** [sos-berlin/js7#12] opened 2024-05-15 14:17 UTC
Calling agent_credential_value.cmd fail with following message 

java.lang.NoClassDefFoundError: com/google/common/base/Splitter
        at com.sos.commons.credentialstore.keepass.SOSKeePassPath.<init>(SOSKeePassPath.java:66)
        at com.sos.commons.credentialstore.keepass.SOSKeePassDatabase.loadFromUri(SOSKeePassDatabase.java:344)
        at com.sos.commons.credentialstore.keepass.SOSKeePassDatabase.getProperty(SOSKeePassDatabase.java:286)
        at com.sos.commons.credentialstore.keepass.SOSKeePassDatabase.main(SOSKeePassDatabase.java:445)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Splitter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more

**Comment by kregory** [comment] 2024-05-16 10:39
I resolved my issue by adding guava.jar and failureaccess.jar into the lib/patch directory in the agent home
from https://github.com/google/guava/releases

**Comment by sosap** [comment] 2024-05-21 10:59
Thank you, the issue is confirmed with

[JITL-741: Keepass support is broken](https://change.sos-berlin.com/browse/JITL-741)

The issue will be fixed with the next maintenance release 2.7.1

**Comment by sosap** [comment] 2024-08-01 22:05
[Release 2.7.1](https://kb.sos-berlin.com/display/PKB/Release+2.7.1) is available since 2024-07-08.

**Closed by sosap** 2024-08-01 22:05 UTC
Labels: bug
